<?php
require_once __DIR__ . '/../includes/security_init.php';
session_start();
require_once '../config/config.php';
require_once '../Login/Login/db.php';

if (!isset($_SESSION['admin_logged_in']) || $_SESSION['admin_logged_in'] !== true) {
    header("Location: ../Login/Login/login.php");
    exit();
}

// Set admin_id for compatibility
if (!isset($_SESSION['admin_id'])) {
    $_SESSION['admin_id'] = 1;
}

// Set headers for CSV download
header('Content-Type: text/csv');
header('Content-Disposition: attachment; filename="ideanest_admin_overview_' . date('Y-m-d_H-i-s') . '.csv"');

// Create output stream
$output = fopen('php://output', 'w');

// Add CSV headers
fputcsv($output, ['IdeaNest Admin Overview Report - ' . date('Y-m-d H:i:s')]);
fputcsv($output, ['Generated by: Admin Panel']);
fputcsv($output, []);

// Enhanced Statistics
fputcsv($output, ['=== SYSTEM STATISTICS ===']);
fputcsv($output, ['Metric', 'Value', 'Details']);

$stats_query = "SELECT 
    COUNT(*) as total_users,
    COUNT(CASE WHEN role = 'student' THEN 1 END) as students,
    COUNT(CASE WHEN role = 'mentor' THEN 1 END) as mentors
    FROM register";
$stats = $conn->query($stats_query)->fetch_assoc();

$subadmin_count = $conn->query("SELECT COUNT(*) as count FROM subadmins")->fetch_assoc();
$stats['subadmins'] = $subadmin_count['count'];

// Project statistics from both tables
$project_stats = $conn->query("SELECT 
    COUNT(*) as total,
    COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending,
    COUNT(CASE WHEN status = 'approved' THEN 1 END) as approved,
    COUNT(CASE WHEN status = 'rejected' THEN 1 END) as rejected
    FROM projects")->fetch_assoc();

$admin_project_stats = $conn->query("SELECT COUNT(*) as admin_approved FROM admin_approved_projects")->fetch_assoc();

// Ideas statistics
$idea_stats = $conn->query("SELECT 
    COUNT(*) as total_ideas,
    COUNT(CASE WHEN status = 'pending' THEN 1 END) as pending_ideas,
    COUNT(CASE WHEN status = 'in_progress' THEN 1 END) as in_progress_ideas,
    COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed_ideas
    FROM blog")->fetch_assoc();

// Mentor activity statistics
$mentor_stats = $conn->query("SELECT 
    COUNT(DISTINCT mentor_id) as active_mentors,
    COUNT(*) as total_sessions,
    COUNT(CASE WHEN status = 'completed' THEN 1 END) as completed_sessions
    FROM mentoring_sessions")->fetch_assoc();

fputcsv($output, ['Total Users', $stats['total_users'], $stats['students'] . ' Students, ' . $stats['mentors'] . ' Mentors']);
fputcsv($output, ['Students', $stats['students'], 'Active student accounts']);
fputcsv($output, ['Mentors', $stats['mentors'], 'Registered mentors']);
fputcsv($output, ['Subadmins', $stats['subadmins'], 'Active subadmin accounts']);
fputcsv($output, ['Total Projects', $project_stats['total'] + $admin_project_stats['admin_approved'], 'All project submissions']);
fputcsv($output, ['Pending Projects', $project_stats['pending'], 'Awaiting review']);
fputcsv($output, ['Approved Projects', $project_stats['approved'], 'Subadmin approved']);
fputcsv($output, ['Admin Approved Projects', $admin_project_stats['admin_approved'], 'Final admin approval']);
fputcsv($output, ['Rejected Projects', $project_stats['rejected'], 'Not approved']);
fputcsv($output, ['Total Ideas', $idea_stats['total_ideas'], 'Project ideas submitted']);
fputcsv($output, ['Completed Ideas', $idea_stats['completed_ideas'], 'Ideas marked as completed']);
fputcsv($output, ['Mentor Sessions', $mentor_stats['total_sessions'], $mentor_stats['completed_sessions'] . ' completed']);

fputcsv($output, []);
fputcsv($output, ['=== USER DETAILS WITH ACTIVITY ===']);
fputcsv($output, ['ID', 'Name', 'Email', 'Role', 'Department', 'Enrollment', 'Phone', 'Projects Submitted', 'Ideas Submitted', 'Email Notifications', 'GitHub Connected']);

$users = $conn->query("
    SELECT r.*, 
           COUNT(DISTINCT p.id) as project_count,
           COUNT(DISTINCT b.id) as idea_count
    FROM register r
    LEFT JOIN projects p ON r.id = p.user_id
    LEFT JOIN blog b ON r.id = b.user_id
    GROUP BY r.id
    ORDER BY r.id DESC
");

while ($user = $users->fetch_assoc()) {
    fputcsv($output, [
        $user['id'],
        $user['name'],
        $user['email'],
        ucfirst($user['role']),
        $user['department'] ?? 'N/A',
        $user['enrollment_number'],
        $user['phone_no'] ?? 'N/A',
        $user['project_count'],
        $user['idea_count'],
        $user['email_notifications'] ? 'Enabled' : 'Disabled',
        !empty($user['github_token']) ? 'Yes' : 'No'
    ]);
}

fputcsv($output, []);
fputcsv($output, ['=== RECENT PROJECT SUBMISSIONS ===']);
fputcsv($output, ['ID', 'Project Name', 'User Name', 'Type', 'Status', 'Submission Date']);

$recent_projects = $conn->query("
    SELECT p.*, r.name as user_name
    FROM projects p
    LEFT JOIN register r ON p.user_id = r.id
    ORDER BY p.submission_date DESC
    LIMIT 50
");

while ($project = $recent_projects->fetch_assoc()) {
    fputcsv($output, [
        $project['id'],
        $project['project_name'],
        $project['user_name'] ?? 'Unknown',
        $project['project_type'],
        ucfirst($project['status']),
        $project['submission_date']
    ]);
}

fputcsv($output, []);
fputcsv($output, ['=== SUBADMIN ACTIVITY SUMMARY ===']);
fputcsv($output, ['ID', 'Name', 'Email', 'Domain', 'Status', 'Requests Made', 'Created Date']);

$subadmins = $conn->query("
    SELECT s.*, 
           COUNT(scr.id) as request_count
    FROM subadmins s
    LEFT JOIN subadmin_classification_requests scr ON s.id = scr.subadmin_id
    GROUP BY s.id
    ORDER BY s.created_at DESC
");

while ($subadmin = $subadmins->fetch_assoc()) {
    fputcsv($output, [
        $subadmin['id'],
        $subadmin['name'] ?? 'N/A',
        $subadmin['email'],
        $subadmin['domain'] ?? 'N/A',
        ucfirst($subadmin['status']),
        $subadmin['request_count'],
        $subadmin['created_at']
    ]);
}

fputcsv($output, []);
fputcsv($output, ['=== EXPORT SUMMARY ===']);
fputcsv($output, ['Report Generated', date('Y-m-d H:i:s')]);
fputcsv($output, ['Total Records Exported', $stats['total_users'] + $stats['subadmins']]);
fputcsv($output, ['Data Includes', 'Users, Projects, Ideas, Subadmin Activities']);
fputcsv($output, ['For Complete Export', 'Use Comprehensive Export option']);

fclose($output);
exit();
